config/routes.rb
Rails.application.routes.draw do

  resources :posts do
   resources :comments
  end
   

end

app/models/comment.rb
class Comment < ActiveRecord::Base
 belongs_to :post
 validates_presence_of :post_id
 validates_presence_of :body
end

app/models/post.rb
class Post < ActiveRecord::Base
 has_many :comments, dependent: :destroy
 validates_presence_of :title
 validates_presence_of :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params) 

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @post, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
        format.js
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:post_id, :body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate, except: [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end

  def authenticate
   authenticate_or_request_with_http_basic do |name,password|
    name == "admin" && password == "secret"
   end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
 <%= div_for comment do %>
  <p>
  <strong>Posted <%= time_ago_in_words(comment.created_at) %> ago</Strong><br />
<%= h(comment.body) %>
</p>
<% end %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.number_field :post_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/create.js.erb
var new_comment = $("<%= escape_javascript(render(:partial => @comment))%>").hide();
$('#comments').prepend(new_comment);
$('#comment_<%= @comment.id %>').fadeIn('slow');
$('#new_comment')[0].reset();

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.post_id %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @comment.post_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Happy birthday</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>
<body>
<div class="shank">
<br>
<div id='cssmenu'>
<ul>
   <li class='active'><a href='/posts'><span>Home</span></a></li>
   <li><a href='http://youtu.be/30AErTZe2lU'><span>Video</span></a></li>
   <li class='last'><a href='https://www.facebook.com/honeyslawyer'><span>Contact</span></a></li>
</ul>
</div>
<br>
<div id="headings">
<h1>Happy birthday!!</h1>
<h3>Dedicated to you by your loved ones!</h3>
</div>
<br>
<br>
</div>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="container-fluid">
<div class="sucess">
<h1>Editing post</h1>
<%=form_tag(@post,id: "edit_post_#{@post.id}",class: "edit_post", method: "patch", role: "form") do %>
   <div class="field">
   <%= label_tag("post_title", "Written By",) %>
   <%= text_field_tag("post[title]", @post.title, class: "form-control",placeholder: "Text input") %>
   </div>
   <br>
   <div class="field">
   <%= label_tag("exampleInputEmail1", "Body") %>
   <%= text_area_tag("post[body]", @post.body, class: "form-control",rows: "3", placeholder: "Text input") %>
   </div>
   <br>
   <div class="actions">
    <%= submit_tag("Update Post") %>
    </div>
<% end %>
<br>
<%= link_to 'Show', @post, class: "btn btn-success btn-lg active" , role: "button" %>
<br>
<br>
<%= link_to 'Back', posts_path, class: "btn btn-info btn-lg active" , role: "button" %>
</div>
</div>

app/views/posts/index.html.erb
<div class="container-fluid">
<br>
<%= link_to 'New Post', new_post_path , class: "btn btn-primary btn-lg active" , role: "button" %>
<br>
<br>
<div class="table-responsive">
<table class="table table-striped table-hover">
  <thead>
    <tr class="info">
      <th>Written by</th>
      <th>Body</th>
      <th>Utilities</th>
      <th></th>
      <th></th>
      
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td class="success"><%= post.title %></td>
        <td class="success"><%= post.body.at(0..20)+"......." %></td>
        <td class="success"><%= link_to "Show", post , class: "btn btn-success btn-lg active" , role: "button" %></td>
        <td class="success"><%= link_to 'Edit', edit_post_path(post) , class: "btn btn-info btn-lg active" , role: "button" %></td>
        <td class="success"><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-lg active" , role: "button" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>

app/views/posts/new.html.erb
<div class="container-fluid">
<div class="sucess">
<h1>New post</h1>
<%=form_tag(@post,id: "edit_post_#{@post.id}",class: "new_post", role: "form") do %>
   <div class="field">
   <%= label_tag("post_title", "Written By",) %>
   <%= text_field_tag("post[title]", @post.title, class: "form-control",placeholder: "Text input") %>
   </div>
   <br>
   <div class="field">
   <%= label_tag("exampleInputEmail1", "Body") %>
   <%= text_area_tag("post[body]", @post.body, class: "form-control",rows: "3", placeholder: "Text input") %>
   </div>
   <br>
   <div class="actions">
    <%= submit_tag("Create Post") %>
    </div>
<% end %>
<br>
<%= link_to 'Back', posts_path, class: "btn btn-info btn-lg active" , role: "button" %>

app/views/posts/show.html.erb
 <p id="notice"><%= notice %></p>




<div class="container-fluid">
<p class="lead">
<blockquote>
  <p class="text-success">
  <%= @post.body %>
  </p>
  <footer>Written By: <cite title="Source Title"><%= @post.title %></cite></footer>
</blockquote>
<br>
<br>
<p>
<h4>Comments:</h3>
<div id="comments">
<%= render partial: @post.comments.reverse %>
</div>
<hr>

<%= form_for([@post, Comment.new], remote: true , role: "form") do |f| %>
  <div class="field">
  <p><%= f.label :body, "New Comment" %><br><br>
     <%= f.text_area :body , class: "form-control",rows: "3", placeholder: "Text input" %>
  </p>
  <p><%= f.submit "Add Comment" %></p>
  </div>
<% end %>

<%= link_to 'Edit',edit_post_path(@post) , class: "btn btn-info btn-lg active" , role: "button" %>
<br>
<br>
<%= link_to 'Back', posts_path, class: "btn btn-success btn-lg active" , role: "button" %>
</div>